version: 2.1
#orbs:
#  coveralls: coveralls/coveralls@1.0.4
jobs:
  build:
    working_directory: ~/optionsprotocol
    docker:
      - image: circleci/node:10.18.0
      - image: trufflesuite/ganache-cli:v6.7.0
        command: ganache-cli --deterministic -e 300 -p 8545 -m 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --accounts 30 --allowUnlimitedContractSize
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Lint Contracts
          command: npm run lint:sol
      - run:
          name: Deploy Contracts
          command: npm run deploy:development
      - run:
          name: Test Contracts
          command: npm run test | tee test_output
      - store_artifacts:
          path: /test_output
      # NOTE -> This requires a paid CircleCI plan to increase the RAM size up to 6/8GB. Fails at current
      #- run:
      #    name: Produce Coverage Report
      #    command: npm run coverage
      #- coveralls/upload
      #- store_artifacts:
      #    path: /coverage
      #- store_artifacts:
      #    path: /.coverage.json
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules


